Repository RocketMap/RocketMap, pull requests merged in 2018-02, with the labels that each got.

#2486 Update pgoapi.
  requirements.txt
Labels: enhancement, minor

#2481 SSL Docs
  docs/_static/img/9xbiv2UN4a5oCt.png
  docs/_static/img/Th9KF0ZsBfyJAo.png
  docs/_static/img/VPhjPMgCUtZanU.png
  docs/_static/img/nT3OAoUuhPI2Ow.png
  docs/_static/img/oCPPqtjgT2RkDa.png
  docs/_static/img/wfIe96O0pAPyzt.png
  docs/extras/letsencrypt-nocertbot.md
  docs/extras/letsencrypt.md
  docs/extras/ssl-guide.md
Labels: awaiting review, documentation

#2492 Fix SSL Docs
  docs/extras/letsencrypt.md
Labels: awaiting review, documentation

#2471 Update custom.js: add default Pokémon to "Hide Pokémon".
  docs/extras/custom-js.md
Labels: documentation, minor, pending changes

#2494 Add fetch_all_news to RPC login sequence.
  pogom/account.py
Labels: awaiting review, important, minor

#2497 Open Google Maps link in app instead of browser.
  static/js/map.js
Labels: awaiting review, enhancement, front-end, minor
