Repository RocketMap/RocketMap, pull requests merged in 2018-03, with the labels that each got.

#2440 Potential EX gym detection
  docs/_static/img/exg.png
  docs/_static/img/exgg.png
  docs/_static/img/exgr.png
  docs/extras/ex-raids.md
  docs/first-run/commandline.md
  pogom/models.py
  pogom/osm.py
  pogom/utils.py
  requirements.txt
  runserver.py
  static/js/map.common.js
  static/js/map.js
  templates/map.html
Labels: awaiting review, breaking change, db migration, new feature

#2501 Add shiny field to db for gym pokemon
  pogom/models.py
Labels: awaiting review, db migration, enhancement

#2414 Weather
  pogom/models.py
  static/images/weather/weather_clear_day.png
  static/images/weather/weather_clear_night.png
  static/images/weather/weather_cloudy.png
  static/images/weather/weather_fog.png
  static/images/weather/weather_partly_cloudy_day.png
  static/images/weather/weather_partly_cloudy_night.png
  static/images/weather/weather_rain.png
  static/images/weather/weather_snow.png
  static/images/weather/weather_windy.png
  static/js/map.js
Labels: awaiting review, important, new feature

#2505 0.91.2
  pogom/utils.py
  runserver.py
Labels: awaiting review, enhancement, minor

#2503 Make Pokémon weather boosted condition a significant field.
  pogom/webhook.py
Labels: awaiting review, enhancement, minor

#2508 Add DB execution context for gym_park.
  pogom/models.py
Labels: awaiting review, bug, minor

#2512 Fix TTH count for one-hour spawns.
  pogom/models.py
  pogom/schedulers.py
Labels: awaiting review, bug, minor

#2502 Replace weather images with emojis.
  static/images/weather/weather_clear_day.png
  static/images/weather/weather_clear_night.png
  static/images/weather/weather_cloudy.png
  static/images/weather/weather_fog.png
  static/images/weather/weather_partly_cloudy_day.png
  static/images/weather/weather_partly_cloudy_night.png
  static/images/weather/weather_rain.png
  static/images/weather/weather_snow.png
  static/images/weather/weather_windy.png
  static/js/map.js
  static/sass/layout/_pokemon.scss
Labels: awaiting review, front-end, minor

#2488 Add Deoxys and Castform's weather forms.
  static/js/map.js
Labels: awaiting review, enhancement, front-end, minor

#2383 Database Cleanup (#2281 rework)
  docs/first-run/commandline.md
  pogom/app.py
  pogom/models.py
  pogom/search.py
  pogom/utils.py
  runserver.py
Labels: awaiting review, breaking change, enhancement, important, new feature

#2479 Status Page: Add account busy/idle to instances.
  pogom/search.py
  static/js/status.js
Labels: awaiting review, enhancement, minor

#2513 Update gender on encounter.
  pogom/models.py
Labels: awaiting review, enhancement, minor

#2509 Only spin stops with levelup script
  tools/levelup.py
Labels: awaiting review, bug, minor

#2516 Change encounter data update.
  pogom/models.py
Labels: bug, confirmed, minor

#2517 Re-add #2513. Confirmed working.
  pogom/models.py
Labels: awaiting review, minor

#2519 Improvements to level-up script.
  tools/levelup.py
Labels: awaiting review, enhancement, minor

#2520 Fix typo in tutorial.md.
  docs/first-run/tutorial.md
Labels: documentation, minor

#2521 Exit script if no cells are in the geofenced area.
  pogom/schedulers.py
Labels: awaiting review, bug, minor

#2525 Log correct amount of dropped items.
  pogom/account.py
Labels: awaiting review, bug, minor

#2529 Fix typo in -DCf docs.
  docs/first-run/commandline.md
  pogom/utils.py
Labels: awaiting review, documentation, important, minor

#2531 Remove tools/spawnpoint-clustering
  tools/spawnpoint-clustering/README.md
  tools/spawnpoint-clustering/cluster.py
  tools/spawnpoint-clustering/utils.py
Labels: confirmed, minor

#2361 Update fr.json.
  .editorconfig
  static/locales/fr.json
Labels: awaiting review, minor

#2493 Update ko.json.
  static/locales/ko.json
Labels: awaiting review, minor

#2463 Add Log Filename
  config/config.ini.example
  docs/first-run/commandline.md
  pogom/utils.py
  runserver.py
Labels: awaiting review, new feature

#2536 Update pgoapi: Pin protobuf to 3.5.1.
  requirements.txt
Labels: awaiting review, bug, minor

#2534 Improve --dump censor.
  pogom/utils.py
Labels: awaiting review, enhancement, minor

#2533 Remove Trainer table and old db migration from RocketMap.
  docs/extras/gyminfo.md
  docs/extras/webhooks.md
  pogom/models.py
  static/js/map.js
  static/sass/layout/_gym-details.scss
Labels: awaiting review, breaking change, db migration, important

#2537 Allow custom hashing service + higher key values.
  pogom/models.py
  pogom/utils.py
  runserver.py
Labels: awaiting review, db migration, new feature

#2535 When hashing quota is exceeded, sleep until quota gets reset.
  pogom/pgorequestwrapper.py
Labels: awaiting review, enhancement, minor

#2539 Fix Markdown Syntax on DigitalOcean Guide
  docs/advanced-install/digital-ocean.md
Labels: awaiting review, documentation, minor

#2543 Support -hs in level-up tool.
  pogom/utils.py
  runserver.py
Labels: awaiting review, bug, minor

#2540 Efficiently exclude hidden Pokemon
  pogom/app.py
  pogom/models.py
Labels: awaiting review, enhancement, important

#2546 Optionally rely on BossLand headers.
  pogom/pgorequestwrapper.py
  pogom/utils.py
Labels: awaiting review, breaking change, bug, minor, new feature
